version: '3.8'
services:
  
  java_app:
    container_name: java_app
    build: ./REST_API
    environment:
      - DB_URL=jdbc:mysql://db:3306/InHome
      - DB_PWD=password
      - DB_USER=api
    expose:
      - "8443"
    ports:
      - "8443:8443"
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'InHome'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./setup.sql:/docker-entrypoint-initdb.d/setup.sql
    command: --init-file /docker-entrypoint-initdb.d/setup.sql

# Names our volume
volumes:
  my-db:
  setup.sql: